baseurl = "https://rhizone.net"
title = "Rhizone"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]
disableLogo = true

[params]
  logoImage = "Albumcover.jpg"
  copyrightText = "rhizonemusic@gmail.com"
  customCSS = "custom.css"